### ISSUE TITLE
Images 0.5.0 breaks travis

### ISSUE THREAD

**Issue by ninegua** [IntelLabs/ParallelAccelerator.jl#10]
It depends on ImageMagick, which is not found on travis system. Shall we go back to Images 0.4.5? @lkuper

**Comment by timholy** [comment]
Just add a `test/REQUIRE` file with
```
ImageMagick
```

**Comment by ninegua** [comment]
Thanks for the suggestion, but that doesn't seem to work out. I had to add this package to .travis.

**Comment by timholy** [comment]
Sorry, I didn't look to see how you ran your tests and just assumed it was `Pkg.test("ParallelAccelerator")`. (It's `Pkg.test` that checks for the `test/REQUIRE` file.) Your solution works fine, glad you were able to solve it.

**Comment by lkuper** [comment]
I'm confused -- if `Images` depends on `ImageMagick`, shouldn't `ImageMagick` appear in https://github.com/timholy/Images.jl/blob/master/REQUIRE ?

**Comment by timholy** [comment]
No, because Images doesn't depend on ImageMagick for any of its own functionality. For example, if all you need to do is load Netpbm files, then [Netpbm.jl](https://github.com/JuliaIO/Netpbm.jl) is the only package you'll need.

Some people have been asking for quite a long time to have a version of Images that has no I/O, because the I/O part has been troublesome (binary dependencies, grr....) and all they want to do is use the algorithms in the package. This new release finally achieves a clean separation between I/O and all the other components of Images.

**Comment by timholy** [comment]
I should have added, all the I/O facilities come courtesy of [FileIO](https://github.com/JuliaIO/FileIO.jl).

**Comment by lkuper** [comment]
@timholy I see.  ParallelAccelerator doesn't depend on Images (or DocOpt) for any of its own functionality, either, but we put them both in the `REQUIRE` file for our package because the examples depend on them.  @ninegua I'd rather list all the examples' dependencies in one place.  The other dependencies are in https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/REQUIRE.  Alternatively, we could have .travis.yml install them all.

**Comment by KristofferC** [comment]
I think the idiomatic way to do it is to put the test requirements in `test/REQUIRE` and then run the travis tests with `Pkg.runtest()`. In that way, the test dependencies should be automatically installed when testing is performed but not when the package is being used normally.

Please correct me @timholy if I am mistaken.

**Comment by lkuper** [comment]
@KristofferC The trouble is that Travis runs not only our tests, but also our examples, and we're talking about the examples' dependencies.  (I guess you could argue that if something has to work in order for Travis to be green, then it is a "test", though.)

**Comment by KristofferC** [comment]
Yes, I would say that if you require that the examples run successfully for a passed C.I then they are also a part of the test suite.

Couldn't you just change so the examples are run from `runtests.jl` instead of calling them directly in the `.travis.yml`?

**Comment by lkuper** [comment]
@KristofferC That was in fact what we did originally.  We switched to having the examples run only on Travis because people want to be able to run a quick coherence check before committing, and then have a more extensive suite of tests run on Travis.  It takes a long time for all the examples to run.

**Comment by KristofferC** [comment]
You could check if you are running on a C.I system (most of them set the environment variable `CI=true`, see: http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables)
and thus condition the examples on `haskey(ENV, "CI")`

**Comment by lkuper** [comment]
@KristofferC Good point. Yes, we can do that and then use `test/REQUIRE`.

**Comment by lkuper** [comment]
@KristofferC After playing around with it a bit more, I think the downside of putting the examples' dependencies in `test/REQUIRE` is that they'll be installed at (and removed at the end of) testing time, every time, whether or not we're running on CI, and all that takes a long time, especially since one of them pulls in Homebrew.  If `Pkg.test` takes too long, people just won't use it.  So I think either we need to put all the examples' dependencies in the top-level `REQUIRE` (which is what we were already doing for the other dependencies), or we need to have .travis.yml install them all.  (I prefer the former, since then anyone will be able to run any of the examples right out of the box once they've installed the package and its deps.)



Done.  The only not-so-great thing about this approach is that it requires people who want to run the tests locally to install ImageMagick even if they're only running the local tests.  But arguably, everyone working on the package should have ImageMagick installed anyway, because we all ought to at least be *able* to run all the examples locally, even if we don't do it regularly.
