### ISSUE TITLE
Fusion and possibly liveness bug

### ISSUE THREAD

**Issue by ninegua** [IntelLabs/ParallelAccelerator.jl#54]
The following program runs correctly with no fusion, but if the `PIRFuseLimit` call is removed, it crashes due to uninitialized array, and from the output it looks like the variable `spikes` is removed from fused code when it shouldn't have been.

~~~
using ParallelAccelerator

ParallelAccelerator.ParallelIR.PIRSetFuseLimit(0)

const dt = 0.001
const t_rc = 0.123
const t_ref = 0.5

@acc function run_neurons(input,v,ref)
    w = v .+ (input .- v) .* dt ./ t_rc
    wMask = w .>= 0
    v[wMask] = w[wMask]
    v[w .< 0] = 0
    refMask = ref .> 0
    v[refMask] = 0
    ref[refMask] = (ref .- dt)[refMask]
    spikes = v .> 1
    v[spikes] = 0
    ref[spikes] = t_ref
    return spikes
end


srand(0)
S = 10
I = randn(S); I1 = copy(I)
V = randn(S); V1 = copy(V)
R = randn(S); R1 = copy(R)
r1 = run_neurons(I, V, R)
r2 = @noacc run_neurons(I1, V1, R1)

println("check diff V ", sum(V .- V1))
println("check diff R ", sum(R .- R1))
println("check diff result ", sum(r1 .- r2))
~~~

**Comment by DrTodd13** [comment]
Fixed in e3d277b..c6c1a61.

v[refMask] needed to create an associate between Range(refMask) and refMask itself and by transitivity ref.  With this fix, all arrays/masks go into the same equivalence class.

Also changed LivenessAnalysis in CompilerTools to include array params again as live out of the final block so that arraysets of v and ref are not optimized away during fusion.

Fixed bug in fusion where the computation of the items defined in the first parfor (itself a result of a previous fusion) needed to take into account all the statements fused into the previous parfor.
